### PR TITLE
Add dispatch-job ACL and update versions

### LINKED ISSUE #28: Can not run job if ACL was enabled
```
Apr 02 15:10:12 ip-172-31-18-211 nomad[936]:     2024-04-02T15:10:12.682Z [DEBUG] http: request failed: method=PUT path=/v1/jobs?region=xx error="Permission denied" code=403
Apr 02 15:10:12 ip-172-31-18-211 nomad[936]: http: request failed: method=PUT path=/v1/jobs?region=planitar error="Permission denied" code=403
Apr 02 15:10:12 ip-172-31-18-211 nomad[936]:     2024-04-02T15:10:12.683Z [DEBUG] http: request complete: method=PUT path=/v1/jobs?region=xx duration=70.024224ms
Apr 02 15:10:12 ip-172-31-18-211 nomad[936]: http: request complete: method=PUT path=/v1/jobs?region=xx duration=70.024224ms
```

```
$ nomad job run -check-index 0 -var="project_name=pn53" derived-src/services/cluster.hcl
Error submitting job: Unexpected response code: 403 (Permission denied)
```

https://github.com/hashicorp/learn-nomad-cluster-setup/blob/main/shared/config/nomad-acl-user.hcl
```hcl
agent {
    policy = "read"
}

node {
    policy = "read"
}

namespace "*" {
    policy = "read"
    capabilities = ["submit-job", "read-logs", "read-fs"]
}

```

This is not clear how client can submit job (eg. write) if it has only `read` policy?

### PR DESCRIPTION
**Pull request by david-yu**
Found that tutorials such as https://developer.hashicorp.com/nomad/tutorials/get-started/gs-deploy-job were not working due to ACLs missing. Also updating to latest versions available for Consul, Vault, Nomad, and Consul-template. Fixes #28

### CODE REVIEW

**Comment by david-yu** [comment]
Somehow the boostrap ACL tokens is not being retrieved from Consul after upgrading versions to 1.18.1

**Comment by david-yu** [comment]
This works now.

**Comment by david-yu** [comment]
Vault 1.16.0 works just not 1.16.1 likely due to https://github.com/hashicorp/nomad/issues/20298

**Comment by david-yu** [comment]
Updated to Vault 1.16.2 and verified that it works

**Comment by krastin** [comment]
Since this is a PR from a private fork I couldn't edit, I've incorporated changes form this PR into the following one

https://github.com/hashicorp/learn-nomad-cluster-setup/pull/31

**Pull request closed without merging**
